### ISSUE TITLE
Research bot configuration with custom commands

### ISSUE THREAD

**Issue by gen1us2k** [maddevsio/comedian#5]

**Comment by malikim** [comment]
Research

Reserch conducted on the official website
https://api.slack.com

bot users and slash teams - it's completely different things in the slack (after the telegram it was not obvious to me)

in the process it turned out that Slack has two versions of Api:

old version:
- https://api.slack.com/tutorials/your-first-slash-command
- https://api.slack.com/custom-integrations/slash-commands

You are browsing the tutorial on traditional user integration, the older way for teams to embed into their Slack team. To reliably use the latest platform features, such as message buttons and event APIs, integrate internal integration as part of the Slack application only for your team. To begin.

new application slack:

- https://api.slack.com/slash-commands

The new version supports working with buttons in messages and etc.

I would look in the direction of a new api, tk there is more pros and the likelihood of support

In order to implement commands through a slash with a new api, you need to make a bot app
there are 2 types of slack app

Distributed - if you upload to the App Store
-load of requirements, authorization through oauth and etc
internal integration (for internal use)
-all pros, but do not need oauth and stuff.

https://api.slack.com/apps/new

in the current situation, the option of internal integration is suitable (for internal use, fewer problems)

As part of the Slack application, they can be easily installed for your workspace as internal integration or distributed in the world, extend to other workspaces.

**Comment by malikim** [comment]
Work with commands is implemented in tasks  #33, #34, #35, #36, #37, #38
