### ISSUE TITLE
Modify date input to take chat timezone into account

### ISSUE THREAD

**Issue by malikim** [maddevsio/comedian#75]

**Comment by anatoliyfedorenko** [comment]
Currently date input takes time, parses it into hours and minutes and then creates Unix time stamp with current data and local hours and minutes. When submitted to DB it converts local time to UTC time, so that UTC time is stored in DB. 
See https://github.com/maddevsio/comedian/commit/e4d09834501b73e262ccbb2e2fbeb0fc746de59a for reference
